### ISSUE TITLE
Improve the README.md file

### ISSUE THREAD

**Issue by demonicirfan** [HackrackClub/BookMyShow-Clone#1]
Make a good README.md file that is easy to understand. Use some images and also improve the setup guide

**Comment by muskanbagrecha** [comment]
I want to take this up.

**Comment by SugatoBagchi** [comment]
Sure. Yours

> I want to take this up.

**Comment by gaurav147-star** [comment]
can i make readme more interactive?if u this me @SugatoBagchi

**Comment by demonicirfan** [comment]
Yes sure go for it, if we like your changes we will merge them too
