### ISSUE TITLE
Change the logo to PNG

### ISSUE THREAD

**Issue by SugatoBagchi** [HackrackClub/BookMyShow-Clone#15]
Check out this logo: 

![image](https://user-images.githubusercontent.com/68023376/135765915-1e254197-fcd9-4dca-a2c5-bcfc1182c754.png)

We need a PNG version of this logo with a white(transparent to be precise) background. But the texts should be white and the red box should also be present there.

You can check out this logo for reference: 

![image](https://user-images.githubusercontent.com/68023376/135765963-199d13fd-aa60-45f8-ae49-ff0e718fbeac.png)

This is how it should look at the website.

![image](https://user-images.githubusercontent.com/68023376/135765979-499f8491-64df-4f3a-b5c3-f1d2122aa607.png)

**Comment by ethan-x11** [comment]
I would like to work in this issue.

**Comment by SugatoBagchi** [comment]
Go ahead. Make sure you star and fork the repo.

**Comment by ethan-x11** [comment]
I made a PR. Please check

**Comment by demonicirfan** [comment]
@SugatoBagchi @ethan-x11 guys this is not the logo i was talking about it should have a white text and transparent background, that logo which you have uploaded is already available

**Comment by ethan-x11** [comment]
I will update with the correct one

**Comment by ethan-x11** [comment]
Updated. Please Check.
