### ISSUE TITLE
Links in readme.md are not working

### ISSUE THREAD

**Issue by demonicirfan** [HackrackClub/BookMyShow-Clone#4]
Links in the `readme.md` file do not take us to that section of the file. Change them so that on clicking on particular link we should get to that section of the file. 

![image](https://user-images.githubusercontent.com/74172466/135708822-f161bbd0-1164-4c6c-b62d-f2975aa8392d.png)

**Comment by DelayCoderz** [comment]
i want to try solve this, pls assign me

**Comment by demonicirfan** [comment]
@DelayCoderz assign #4 to you
