### ISSUE TITLE
Changes in CONTRIBUTING.md and README.md

### ISSUE THREAD

**Issue by SugatoBagchi** [HackrackClub/BookMyShow-Clone#6]
Few changes need immediate attention in this project.

1. Change the images in [CONTRIBUTING.md](https://github.com/HackrackClub/BookMyShow-Clone/blob/master/CONTRIBUTING.md) to our repository related image. Eg: in point number 2, it is shown List-of-Learning-Resources image. That should be changed to the BookMyShow-Clone repository image. All other places should be changed as well.
2. Add guidelines regarding the spammy requests and BNBR(Be Nice & Be Respectful) policy.
3. Make a section in [README.md](https://github.com/HackrackClub/BookMyShow-Clone/blob/master/README.md) about Contribution guidelines and link the same to [CONTRIBUTING.md](https://github.com/HackrackClub/BookMyShow-Clone/blob/master/CONTRIBUTING.md)

Feel free to make other changes so that it looks more pretty.

**Comment by Im-Abhi** [comment]
Hey, can I work on this issue.
At first I will make changes in CONTRIBUTING.md

**Comment by Anubha13kumari** [comment]
I want to work on this issue

**Comment by SugatoBagchi** [comment]
@Im-Abhi Sure. Go ahead. Make sure you star and fork the repo.

@Anubha13kumari Feel free to open any other issue which you think needs attention. We will assign it to you.
