### ISSUE TITLE
Add a PULL_REQUEST_TEMPLATE.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by SugatoBagchi** [HackrackClub/BookMyShow-Clone#8]
We need a PULL_REQUEST_TEMPLATE.md and CODE_OF_CONDUCT.md in our project. 

Please add the necessary details. Don't make a blank file PR. You can check out this [PR Template](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/PULL_REQUEST_TEMPLATE.md) and [Code of Conduct Template](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/PULL_REQUEST_TEMPLATE.md) for reference. However, don't just do copy paste else your PR will be labelled invalid.

**Comment by rushalikhilrani** [comment]
I am interested, please assign this issue to me

**Comment by SugatoBagchi** [comment]
@rushalikhilrani Yours.
